# Simulated daily request to your render project so that the service doesn't go down
name: 10-min render ping

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://property-access-json-server.onrender.com/
